title: murmcraft
description: > # this means to ignore newlines until "baseurl:"
  Amigurumien virkkausohjeita.
# social links
github_username:  murmcraft
keywords: Amigurumi, Virkkaus
author: murmcraft
baseurl: "/crochet/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# sidebar
default-image: /img/murmcraft.svg

built-by: murmcraft

copyright:
   name: murmcraft
   link: 'https://murmcraft.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: ""

# Comments
disqus: no
disqus-shortname: ""

#social
#facebook: ""
#quora: ""
#twitter: ""
github: https://github.com/murmcraft
#email: ""

#facebook like box
fb-like-box: no
fb-app-id: ""
fb-page-url: ""
fb-page-title: ""

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

# Bootstrap
bootstrap:
  assets: true
